Sort databases; check profile load

diff --git a/exec/execDBs b/exec/execDBs
--- a/exec/execDBs
+++ b/exec/execDBs
@@ -125,7 +125,7 @@ if [[ ${CONTINUE} == true ]] ; then
   if [[ ${STEP} -le 2 ]] ; then
     DATABASES=$(db2 list db directory | tail -n +6 | awk '/^Database / \
       {if (NR!=1) print ""; next} {printf $0} END {print "a";}' \
-      | awk '/Indirect/ {print $4}')
+      | awk '/Indirect/ {print $4}' | sort)
   fi
   # Modifies the command for evaluation.
   if [[ ${EVAL} == true ]] ; then
@@ -140,8 +140,9 @@ if [[ ${CONTINUE} == true ]] ; then
       TMP_FILE=${TMP_DB_FILE_PREFIX}-${DB}.log
       ERR_FILE=${TMP_DB_FILE_PREFIX}-${DB}.err
       if [[ ${CONNECT} == true ]] ; then
-        ( . ${PROFILE} ; db2 connect to ${DB} > /dev/null ; ${COMMAND} \
-          > ${TMP_FILE} 2> ${ERR_FILE} ) &
+        ( . ${PROFILE} ; db2 connect to ${DB} > /dev/null ; \
+          if [[ $? -eq 0 ]] ; then ${COMMAND} > ${TMP_FILE} 2> ${ERR_FILE} ; \
+          else echo "Error while connecting" > ${ERR_FILE} ; fi ) &
       else
         ( ${COMMAND} > ${TMP_FILE} 2> ${ERR_FILE} ) &
       fi
